services:
  - mongo:3.4

before_script:
  - PHP_VERSION=$(php -r 'echo phpversion();')
  - echo $PHP_VERSION
  - echo "extension = mongodb.so" >> /usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini
  - php -r 'echo MONGODB_VERSION . PHP_EOL;'
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --quiet
  - composer.phar update --no-interaction

test:7.0:
  image: php:7.0
  script:
    - composer test
