sudo: false

language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - "mongo --eval 'db.adminCommand({ setParameter: true, textSearchEnabled : true}).ok === 1'"
  - composer update --no-interaction
  
script:
  - mongod --version
  - php -r "echo \MongoClient::VERSION . PHP_EOL;"
  - mkdir -p log
  - ./vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover log/clover.xml tests
  
after_script:
  - php ./vendor/bin/coveralls -v
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c2a1663759bdb5ddf7a0
    on_success: always
    on_failure: newer
    on_start: false
