sudo: false

dist: trusty

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: nightly
  include:
    - stage: Quality assurance
      env: CODE_COVERAGE
      before_script:
        - mkdir -p build/logs
      script: composer cover
      after_script: composer coveralls
    - stage: Quality assurance
      env: CODE_STANDARDS
      script: composer check-style

services: mongodb

before_script:
  - PHP_VERSION=$(php -r 'echo phpversion();')
  - mongod --version
  - echo $TRAVIS_PHP_VERSION
  - echo $PHP_VERSION
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
  - php -r 'echo MONGODB_VERSION . PHP_EOL;';
  - composer update --no-interaction
  - mkdir -p ./share
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c2a1663759bdb5ddf7a0
    on_success: always
    on_failure: newer
    on_start: false
