sudo: false

language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

services: mongodb

before_script:
  - echo $TRAVIS_PHP_VERSION
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then composer require "alcaeus/mongo-php-adapter" --ignore-platform-reqs; fi
  - composer update --no-interaction
  - "mongo --eval 'db.adminCommand({ setParameter: true, textSearchEnabled : true}).ok === 1'"

script:
  - mongod --version
  - mkdir -p log
  - ./vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover log/clover.xml tests
  
after_script:
  - php ./vendor/bin/coveralls -v
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c2a1663759bdb5ddf7a0
    on_success: always
    on_failure: newer
    on_start: false
