sudo: false

dist: trusty

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

language: php

php:
  - nightly
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: "5.3"
      dist: precise

services: mongodb

before_script:
  - PHP_VERSION=$(php -r 'echo phpversion();')
  - mongod --version
  - if [[ ${PHP_VERSION:0:2} == "5." ]]; then php -r "echo \MongoClient::VERSION . PHP_EOL;"; fi
  - if [[ ${PHP_VERSION:0:2} == "7." ]]; then php -r 'echo MONGODB_VERSION . PHP_EOL;'; fi
  - echo $TRAVIS_PHP_VERSION
  - echo $PHP_VERSION
  - if [[ ${PHP_VERSION:0:2} == "5." ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${PHP_VERSION:0:2} == "7." ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer update --no-interaction
  - if [[ ${PHP_VERSION:0:2} == "7." ]]; then composer require "alcaeus/mongo-php-adapter" --ignore-platform-reqs; fi
  - mkdir -p ./share

script:
  - composer cover
  - composer check-style
  
after_script:
  - composer coveralls
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c2a1663759bdb5ddf7a0
    on_success: always
    on_failure: newer
    on_start: false
