sudo: false

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
  
language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

services: mongodb

before_script:
  - MONGOD_VERSION=$(mongod --version)
  - echo $MONGOD_VERSION
  - if [[ ${MONGOD_VERSION:0:3} == "2.4" ]]; then mongod --setParameter textSearchEnabled=true; fi
  - echo $TRAVIS_PHP_VERSION
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then composer require "alcaeus/mongo-php-adapter" --ignore-platform-reqs; fi
  - composer update --no-interaction
  - mkdir -p ./share

script:
  - composer cover
  - composer check-style
  
after_script:
  - composer coveralls
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c2a1663759bdb5ddf7a0
    on_success: always
    on_failure: newer
    on_start: false
